---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
script:
  - bundle exec rake validate
  - bundle exec rake lint
  - bundle exec rake spec
env:
  - PUPPET_VERSION="3.2.0"
  - PUPPET_VERSION="3.3.0"
  - PUPPET_VERSION="3.4.0"
  - PUPPET_VERSION="3.5.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="3.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="3.7.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="4.0.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="4.1.0" STRICT_VARIABLES=yes
matrix:
  exclude:
  # Ruby 1.8.7 (Puppet 4.0.0 requires ruby 1.9.3 or greater.)
  - rvm: 1.8.7
    env: PUPPET_VERSION="4.0.0" STRICT_VARIABLES=yes
  - rvm: 1.8.7
    env: PUPPET_VERSION="4.1.0" STRICT_VARIABLES=yes
  # Ruby 2.1.0
  - rvm: 2.1.0
    env: PUPPET_VERSION="3.2.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="3.3.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="3.4.0"
